'use client';

import { Button } from '../ui/button';
import { CheckIcon, CopyIcon } from 'lucide-react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { coldarkDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose
} from '../ui/dialog';
import { useEffect, useState } from 'react';

interface CodePreviewModalProps {
  code: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export const CodePreviewModal = ({
  code,
  open,
  onOpenChange
}: CodePreviewModalProps) => {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (copied) {
      setTimeout(() => setCopied(false), 2000);
    }
  }, [copied]);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle>Generated Code</DialogTitle>
          <DialogDescription>
            This code was generated by an AI agent. You can copy it or download
            it.
          </DialogDescription>
        </DialogHeader>
        <div className="max-h-[60vh] overflow-y-auto">
          <SyntaxHighlighter language="html" style={coldarkDark}>
            {code}
          </SyntaxHighlighter>
        </div>
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="secondary">
              Close
            </Button>
          </DialogClose>
          <Button onClick={handleCopy} disabled={copied} variant="outline">
            {copied ? (
              <CheckIcon className="mr-2 h-4 w-4 text-green-500" />
            ) : (
              <CopyIcon className="mr-2 h-4 w-4" />
            )}
            {copied ? 'Copied' : 'Copy Code'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
