
import { Button } from "../ui/button";
import { CopyIcon } from "lucide-react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { coldarkDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose
} from "../ui/dialog";

interface CodePreviewModalProps {
  code: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export const CodePreviewModal = ({
  code,
  open,
  onOpenChange
}: CodePreviewModalProps) => {
  const handleCopy = () => {
    navigator.clipboard.writeText(code);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle>Generated Code</DialogTitle>
          <DialogDescription>
            This code was generated by an AI agent. You can copy it or download
            it.
          </DialogDescription>
        </DialogHeader>
        <div className="max-h-[60vh] overflow-y-auto">
          <SyntaxHighlighter language="html" style={coldarkDark}>
            {code}
          </SyntaxHighlighter>
        </div>
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="secondary">
              Close
            </Button>
          </DialogClose>
          <Button onClick={handleCopy}>
            <CopyIcon className="w-4 h-4 mr-2" />
            Copy Code
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}; 