import { useEmail } from '@/stores/use-email';
import { ArrowLeftIcon, CodeIcon, DownloadIcon } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button } from '../ui/button';
import { Steps } from '@/lib/types';
import { CodePreviewModal } from '../molecules/code-preview-modal';

export const Preview = ({ onNext }: { onNext: (step: Steps) => void }) => {
  const { generatedHtml, fragments } = useEmail();
  const [processedHtml, setProcessedHtml] = useState<string>('');
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    const processHtml = async () => {
      if (!generatedHtml || fragments.length === 0) return;

      let html = generatedHtml;

      const fileToDataUrl = (file: File): Promise<string> => {
        return new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = reject;
          reader.readAsDataURL(file);
        });
      };

      for (const fragment of fragments) {
        try {
          const dataUrl = await fileToDataUrl(fragment.file);
          const baseName = fragment.id.replace(/\.[^/.]+$/, '');
          const regex = new RegExp(
            `src=["'](?:[^"']*/)?${baseName}(?:\\.[^"']*)?["']`,
            'g'
          );
          html = html.replace(regex, `src="${dataUrl}"`);
        } catch (error) {
          console.error(`Error processing fragment ${fragment.id}:`, error);
        }
      }

      setProcessedHtml(html);
    };

    processHtml();
  }, [generatedHtml, fragments]);

  const handleDownload = () => {
    const blob = new Blob([processedHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'email.html';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <section>
      <div className="my-8 space-y-1">
        <h2 className="tracking-light text-[28px] leading-tight font-bold text-[#0d141c]">
          Your email is generated!
        </h2>
        <p className="text-base leading-normal font-normal text-[#0d141c]">
          This email was generated by an AI agent.
        </p>
      </div>

      <div className="overflow-hidden rounded-lg border">
        <iframe
          srcDoc={processedHtml}
          className="h-[600px] w-full"
          title="Email Preview"
        />
      </div>

      <div className="mt-5 flex items-center justify-center gap-4">
        <Button onClick={() => onNext(Steps.CUT_IMAGE)}>
          <ArrowLeftIcon className="mr-2 h-4 w-4" />
          Back to cut image
        </Button>
        <Button onClick={() => setIsModalOpen(true)}>
          <CodeIcon className="mr-2 h-4 w-4" />
          View Code
        </Button>
        <Button onClick={handleDownload}>
          <DownloadIcon className="mr-2 h-4 w-4" />
          Download HTML
        </Button>
      </div>

      <CodePreviewModal
        code={processedHtml}
        open={isModalOpen}
        onOpenChange={setIsModalOpen}
      />
    </section>
  );
};
